# Generated by Django 4.2.8 on 2023-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_alter_userreg_options_alter_userreg_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
