# Generated by Django 4.2.8 on 2023-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_alter_userreg_email_alter_userreg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
