# Generated by Django 4.2.8 on 2023-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_alter_userreg_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreg',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userreg',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
